server:
  port: 8081

spring:
  jpa:
    database: mysql
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties.jadira.usertype.autoRegisterUserTypes: true
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # DATASOURCE
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.20.2.133:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

